on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - run: git fetch --prune --unshallow

      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - uses: actions/setup-go@v2
        with:
          go-version: '^1.19'

      - name: install pre-requisites
        run: |
          sudo apt-get update
          sudo apt-get install -y ruby ruby-dev rubygems build-essential gcc-arm-linux-gnueabi
          sudo gem install --no-document fpm

      - name: build debian packages
        run: |
          make test
          GOARCH=arm GOARM=7 GOOS=linux CGO_ENABLED=1 CC=arm-linux-gnueabi-gcc ARCH=armhf make package

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            build/*armhf.deb
